auto/urls.py
from django.urls import path, include
from auto.views import CarView

urlpatterns = [
    path('', CarView.as_view(), name='index'),
]

smartwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auto.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

auto/models.py
from django.db import models
from django.utils.translation import gettext as _

# Модель таблицы автомобилей
class Car(models.Model):
    TRANS = [
        (1, 'Механика'),
        (2, 'Автомат'),
        (3, 'Робот'),
    ]
    manufacturer = models.CharField(max_length=255,verbose_name=_("Производитель"))
    model = models.CharField(max_length=255,verbose_name=_("Модель"))
    year = models.IntegerField(verbose_name=_("Год выпуска"), null=True, blank=True)
    transmission = models.SmallIntegerField(choices=TRANS, default=1, null=True, blank=True)
    color = models.CharField(max_length=255,verbose_name=_("Цвет"), null=True, blank=True)
    class Meta:
            verbose_name = 'Автомобиль'
            verbose_name_plural = 'Автомобили'
            ordering = ['manufacturer', 'model']
    def __str__(self):
        return "{} {}".format(self.manufacturer, self.model)

auto/views.py
from django.shortcuts import render
from django.views.generic import ListView
from auto.models import Car
from django.db.models import Q, F

class CarView(ListView):
    model = Car
    context_object_name = "cars"
    template_name = "car_list.html"
    def get_queryset(self):
        query = Q()
        if 'manufacturer' in self.request.GET:
            query.add(Q(manufacturer__contains=self.request.GET['manufacturer']), Q.AND)
        if 'model' in self.request.GET:
            query.add(Q(model__contains=self.request.GET['model']), Q.AND)
        if 'year' in self.request.GET:
            if self.request.GET['year']:
                query.add(Q(year=self.request.GET['year']), Q.AND)
        if 'transmission' in self.request.GET:
            query.add(Q(transmission=self.request.GET['transmission']), Q.AND)
        if 'color' in self.request.GET:
            query.add(Q(color__contains=self.request.GET['color']), Q.AND)
        queryset = Car.objects.filter(query)
        return queryset
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['transmissions'] = Car.TRANS
        return context

auto/templates/car_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Список автомобилей</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col">
            </div>
            <div class="col-10">
                <h4 class="mt-3 ml-3 text-uppercase">Список автомобилей</h4>
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <table class="table table-hover mt-3">
                                <thead>
                                    <tr>
                                        <th scope="col">№</th>
                                        <th scope="col">Производитель</th>
                                        <th scope="col">Модель</th>
                                        <th scope="col">Год выпуска</th>
                                        <th scope="col">Коробка передач</th>
                                        <th scope="col">Цвет</th>
                                    </tr>
                                </thead>
                                {% for car in cars %}
                                <tr>
                                    <th>{{forloop.counter}}</th>
                                    <td>{{car.manufacturer}}</td>
                                    <td>{{car.model}}</td>
                                    <td>{{car.year}}</td>
                                    <td>{{car.get_transmission_display}}</td>
                                    <td>{{car.color}}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                        <div class="col-3">
                            <h5 class="mt-3">Фильтр</h5>
                            <form action="/">
                                <label class="col-form-label">Производитель: 
                                    <input name="manufacturer" class="form-control"></label>
                                <label class="col-form-label">Модель: 
                                    <input name="model" class="form-control"></label>
                                <label class="col-form-label">Год выпуска: 
                                    <input type="number" name="year" class="form-control" size="5"></label>
                                <label class="col-form-label">Коробка передач:
                                    <select class="form-control" name="transmission">
                                        <option selected disabled>Выберите коробку</option>
                                        {% for number, name in transmissions %}
                                        <option value={{number}}>{{name}}</option>
                                        {% endfor %}
                                    </select>
                                </label>
                                <label class="col-form-label">Цвет: <input name="color" class="form-control"></label>

                                <input type="submit" value="Фильтр" class="btn btn-primary mt-3">
                                <a href="/" class="btn btn-secondary mt-3">Отменить</a>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
            <div class="col"> </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

</html>